---
- name: make sure heat is in keystone
  hosts: frontend[0]
  gather_facts: True
  sudo: False
  tasks:

    # heat_stack_user role is associated with admin(user)/admin(tenant) 
    # due to the limitation of keystone_user module.
    # This should only create a role without associating it with user/tenant.
    # May be rectified later
    - name: create heat_stack_user role
      keystone_user: 
        endpoint: "{{ keystone_admin_url }}"
        token: "{{ admin_token }}" 
        role: heat_stack_user
        user: admin
        tenant: admin

  
    - name: create heat user in keystone
      keystone_user: 
        endpoint: "{{ keystone_admin_url }}"
        token: "{{ admin_token }}" 
        tenant: "{{ service_tenant }}" 
        user: heat 
        password: "{{ heat_identity_password }}"

    - name: add heat user to the service tenant with the admin role
      keystone_user: 
        endpoint: "{{ keystone_admin_url }}"
        token: "{{ admin_token }}" 
        tenant: "{{ service_tenant }}" 
        user: heat 
        role: admin

    - name: add heat endpoint
      keystone_service: 
        endpoint: "{{ keystone_admin_url }}"
        token: "{{ admin_token }}"
        region: "{{ openstack_region }}"
        name: heat
        type: orchestration
        description: "Orchestration"
        public_url: "{{ heat_public_url }}"
        internal_url: "{{ heat_internal_url }}"
        admin_url: "{{ heat_admin_url }}"


    - name: add heat cloudformation endpoint
      keystone_service: 
        endpoint: "{{ keystone_admin_url }}"
        token: "{{ admin_token }}"
        region: "{{ openstack_region }}"
        name: heat-cfn
        type: cloudformation
        description: "Orchestration CloudFormation"
        public_url: "{{ heat_cfn_public_url }}"
        internal_url: "{{ heat_cfn_internal_url }}"
        admin_url: "{{ heat_cfn_admin_url }}"        
        