---
- name: OpenStack Identity Database for Heat
  hosts: sql_backend[0]
  sudo: True
  gather_facts: True
  tasks:

    - name: ensure heat database is present
      mysql_db: 
        name: heat
        encoding: utf8

    - name: ensure heat database user is present
      mysql_user: 
        name: heat 
        host: "{{ item }}"
        password: "{{ heat_db_password }}"
        priv: heat.*:ALL
      with_items:
        - "%"
        - localhost
