---
- name: OpenStack Image Service (Controller)
  hosts: controller
  sudo: yes

  tasks:
    - name: ensure glance is installed
      yum: name={{ item }} state=latest
      with_items:
        - openstack-glance
        - openstack-utils
        - openstack-selinux
        - sheepdog
        - MySQL-python
      notify:
         - restart glance-registry
    
    - name: ensure glance-registry.conf file file is configured
      template: >
          src=templates/etc/glance/glance-registry.conf
          dest=/etc/glance/glance-registry.conf
          owner=root
          group=glance
          mode=0640
          backup=no
      notify:
         - restart glance-registry

    - name: ensure glance-registry port is opened.
      include: ../reusables/open_firewall_port.yml protocol=tcp port=9191
 
    - name: ensure glance-registry automatically boots after reboot
      service: name=openstack-glance-registry state=started enabled=yes
 

  handlers:
    - include: ../reusables/handlers.yml

    - name: restart glance-registry
      service: name=openstack-glance-registry state=restarted
    
    