---
- name: OpenStack Image Service (Fixture(s))
  hosts: frontend[0]
  sudo: yes

  tasks:
    - name: ensure glance image is registered
      glance_image: 
            auth_url: "{{ keystone_public_url }}"
            copy_from: "{{ item.url }}"
            disk_format: "{{ item.disk_format }}"
            is_public: yes
            login_username: "{{ admin_user }}"
            login_password: "{{ admin_password }}"
            login_tenant_name: "{{ admin_tenant }}"
            name: "{{ item.name}}"
            region_name: "{{ openstack_region }}"
      with_items:  glance_images
            
