---
- name: Install or verify neutron database
  hosts: sql_backend[0]
  sudo: True
  tasks:

    - name: ensure neutron database is present
      mysql_db: 
        name: neutron
        encoding: utf8

    - name: ensure neutron database user is present
      mysql_user: 
        name: neutron 
        host: "{{ item }}" 
        password: "{{ neutron_db_password }}" 
        priv: neutron.*:ALL
      with_items:
        - "%"
        - localhost

