---
- name: Enable notification to ceilometer(Cinder for volume-backend)
  hosts: volume_backend
  sudo: yes

  tasks:
 
    - name: ensure cinder-api to send notification
      ini_file: 
        dest: /etc/cinder/cinder.conf 
        section: "{{ item.section }}" 
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { section: DEFAULT, option: control_exchange, value: cinder }
        - { section: DEFAULT, option: notification_driver, value: cinder.openstack.common.notifier.rpc_notifier }
      notify:
        restart cinder services

      
  handlers:
    - name: restart cinder services
      service: name={{item}} state=restarted
      with_items:
        - openstack-cinder-volume 
  
    