---
- name: OpenStack Compute (Backend)
  hosts: compute_backend
  sudo: yes

  tasks:  
    - name: ensure nova compute packages are installed
      yum: name={{item}} state=latest
      with_items:
        - openstack-nova-compute 
      notify:
        - ensure services are restarted

    
    - name: ensure nova.conf file is configured
      template: >
            src=templates/etc/nova/nova.conf
            dest=/etc/nova/nova.conf
            owner=root group=nova mode=0640 backup=no
      notify:
        - ensure services are restarted
        
    - name: ensure vncserver_proxy address is set to self address
      lineinfile: 
        dest: /etc/nova/nova.conf
        regexp: "vncserver_proxyclient_address="
        line: "vncserver_proxyclient_address={{ my_int_ip }}"
        state: present

    - name: ensure vncserver_listen address is set to self address
      lineinfile: 
        dest: /etc/nova/nova.conf
        regexp: "vncserver_listen="
        line: "vncserver_listen={{ my_int_ip }}"
        state: present        
        
        
        
    - name: ensure virbr0 is absent
      shell: virsh net-destroy default && virsh net-undefine default
      when: "'virbr0' in ansible_interfaces"
      ignore_errors: True
      notify: restart libvirtd

    - name: ensure neutron-server port 5900:5999 is opened
      include: ../reusables/open_firewall_port.yml protocol=tcp port="5900:5999"

    - name: ensure nova-compute automatically boots after reboot
      service: name=openstack-nova-compute state=started enabled=yes
      
  handlers:
    - include: ../reusables/handlers.yml

    - name: restart libvirtd
      service: name=libvirtd state=restarted
    
    - name: ensure services are restarted
      service: name=openstack-nova-compute state=restarted
    
