---
- name: OpenStack Compute (Controller)
  hosts: controller
  sudo: yes

  tasks:    
    - name: ensure nova packages are installed
      yum: name={{item}} state=latest
      with_items:
        - openstack-nova-novncproxy
        - openstack-nova-console
        - openstack-nova-conductor
        - openstack-nova-scheduler
        - python-novaclient
        - openstack-nova-cert
      notify:
        - ensure services are restarted
  
    - name: ensure nova.conf file is configured
      template: >
            src=templates/etc/nova/nova.conf
            dest=/etc/nova/nova.conf
            owner=root group=nova mode=0640 backup=no
      notify:
        - ensure services are restarted
    


    - name: ensure nova port 6080 is opened
      include: ../reusables/open_firewall_port.yml protocol=tcp port=6080
        
    - name: ensure nova port 6081 is opened
      include: ../reusables/open_firewall_port.yml protocol=tcp port=6081
        
    - name: ensure nova services automatically boots after reboot
      service: name={{item}} state=started enabled=yes
      with_items:
        - openstack-nova-consoleauth
        - openstack-nova-console
        - openstack-nova-novncproxy
        - openstack-nova-xvpvncproxy
        - openstack-nova-scheduler
        - openstack-nova-cert
        - openstack-nova-conductor
        - messagebus


  handlers:
    - include: ../reusables/handlers.yml
      
    - name: ensure services are restarted
      service: name={{item}} state=restarted
      with_items:
        - openstack-nova-consoleauth
        - openstack-nova-console
        - openstack-nova-novncproxy
        - openstack-nova-xvpvncproxy
        - openstack-nova-scheduler
        - openstack-nova-cert
        - openstack-nova-conductor
