---
- name: Install or verify nova database
  hosts: sql_backend[0]
  sudo: True
  tasks:

    - name: ensure nova database is present
      mysql_db: 
        name: nova
        encoding: utf8

    - name: ensure nova database user is present
      mysql_user: 
        name: nova 
        host: "{{ item }}" 
        password: "{{ nova_db_password }}" 
        priv: nova.*:ALL
      with_items:
        - "%"
        - localhost

