---
- name: restart services(controller)
  hosts: controller
  serial: 1
  sudo: yes
  gather_facts: no

  tasks:
    - name: ensure CONTROLLER services are restarted
      service: name={{item}} state=restarted
      with_items:
        - openstack-cinder-scheduler
        - openstack-glance-registry
        - openstack-nova-cert
        - openstack-nova-conductor
        - openstack-nova-console
        - openstack-nova-consoleauth
        - openstack-nova-novncproxy
        - openstack-nova-scheduler
        - openstack-nova-xvpvncproxy



        

