---
- name: restart services(frontend)
  hosts: frontend
  serial: 1
  sudo: yes
  gather_facts: no

  tasks:
    - name: ensure FRONTEND services are restarted
      service: name={{item}} state=restarted
      with_items:
        - openstack-keystone 
        - openstack-glance-api
        - openstack-cinder-api
        - neutron-server
        - openstack-nova-api


        

