---
- name: restart services(NW_Gateway)
  hosts: network_gateway
  serial: 1
  sudo: yes
  gather_facts: no

  tasks:
    - name: ensure GATEWAY services are restarted
      service: name={{ item }} state=restarted
      with_items: 
        - neutron-dhcp-agent
        - neutron-linuxbridge-agent
        - neutron-l3-agent
        - neutron-metadata-agent
        - neutron-lbaas-agent


        

