---
- name: Restart RabbitMQ server
  hosts: amqp_backend
  serial: 1
  sudo: yes
  gather_facts: no
  tasks:

    - name: ensure RabbitMQ service is restarted
      service: name={{ item }} state=restarted
      with_items: 
        - rabbitmq-server

        
        