---
- name: OpenStack Identity (Fixture(s))
  hosts: frontend[0]
  gather_facts: yes
  sudo: yes
  tasks:
 
    - name: create service tenant
      keystone_user: 
        endpoint: "{{ keystone_admin_url }}"
        token: "{{ admin_token }}" 
        tenant: "{{ service_tenant }}" 
        tenant_description: "Service Tenant"
  
    - name: add keystone endpoint information
      keystone_service: 
        endpoint: "{{ keystone_admin_url }}"
        token: "{{ admin_token }}" 
        region: "{{ openstack_region }}"
        name: keystone
        type: identity
        description: "Identity Service"
        public_url: "{{ keystone_public_url }}"
        internal_url: "{{ keystone_internal_url }}"
        admin_url: "{{ keystone_admin_url }}"
  
    - name: create admin tenant
      keystone_user: 
        endpoint: "{{ keystone_admin_url }}"
        token: "{{ admin_token }}" 
        tenant: admin
        tenant_description: "Admin Tenant"
  
    - name: create admin user
      keystone_user: 
        endpoint: "{{ keystone_admin_url }}"
        token: "{{ admin_token }}" 
        tenant: admin
        user: admin 
        password: "{{ admin_password }}"
  
    - name: create admin role and associate it with admin user
      keystone_user: 
        endpoint: "{{ keystone_admin_url }}"
        token: "{{ admin_token }}" 
        tenant: admin
        user: admin 
        role: admin
  
    - name: create Member role and associate it with admin user
      keystone_user: 
        endpoint: "{{ keystone_admin_url }}"
        token: "{{ admin_token }}" 
        tenant: admin
        user: admin 
        role: Member

    - name: copy keystone rc file
      template: src={{ item.src }} dest={{ item.dest }} owner=root mode=0700
      with_items:
        - { src: templates/root/keystonerc_admin, dest: /root/keystonerc_admin } 
        - { src: templates/root/openrc, dest: /root/openrc } 
                
  
