---
- name: workaround https://groups.google.com/forum/#!topic/ansible-project/nhYAFkD20z0
  hosts: sql_backend
  sudo: yes
  gather_facts: yes



- name: OpenStack Identity Service
  hosts: frontend
  sudo: yes

  tasks:    
    - name: ensure keystone package is installed
      yum: name={{ item }} state=latest
      with_items:
        - openstack-keystone
        - openstack-utils
        - openstack-selinux
        - MySQL-python
        - memcached
      notify: restart keystone
    
    - name: ensure keystone.conf file is configured
      template: 
          src: templates/etc/keystone/keystone.conf
          dest: /etc/keystone/keystone.conf
          owner: root
          group: keystone
          mode: 0640
      notify: restart keystone

      # keystone_manage cannot used due to lack of migration.py
    - name: ensure keystone database is synchronized
      command: su -s /bin/sh -c "/usr/bin/keystone-manage db_sync" keystone
      #keystone_manage: action=dbsync
      notify: restart keystone
      
    - name: check cert file if public key exists
      action: shell test -e /etc/keystone/ssl/private/signing_key.pem && echo "0" || echo "ng"
      register: is_file_created

    - name: ensure public key for keystone is made
      command: /usr/bin/keystone-manage pki_setup --keystone-user keystone --keystone-group keystone
      when: is_file_created.stdout != "0"
      
    - name: ensure key files are properly chowned
      shell: chown -R keystone:keystone /etc/keystone/ssl
        
    - name: ensure key files are properly chmodded
      shell: chmod -R o-rwx /etc/keystone/ssl

      
    - name: ensure keystone log is properly ownered
      file: path={{ item }} owner=keystone group=keystone state=file
      with_items: 
        - /var/log/keystone/keystone.log

    - name: ensure keystone port 5000 is opened
      include: ../reusables/open_firewall_port.yml protocol=tcp port=5000
 
    - name: ensure keystone port 35357 is opened
      include: ../reusables/open_firewall_port.yml protocol=tcp port=35357
    
    - name: ensure keystone service boots automatically after reboot
      service: name=openstack-keystone state=started enabled=yes
    
    - name: ensure memcached service boots automatically after reboot
      service: name=memcached state=started enabled=yes
    

    - name: ensure expired keystone token deletion is schedules
      cron:
        name: "remove expired token"
        minute: 1
        user: "keystone"
        job: '/usr/bin/keystone-manage token_flush >/dev/null 2>&1'
        state: present    
    
    
    
  handlers:
    - include: ../reusables/handlers.yml

    - name: restart keystone
      service: name=openstack-keystone state=restarted



