---
- name: edit sysconfig/network for VLAN
  hosts: compute_backend:network_gateway
  sudo: yes

  tasks:
    - name: "enable VLAN"
      lineinfile: dest=/etc/sysconfig/network regexp='^VLAN=.*' line="VLAN=yes" state=present
  
    - name: "set VLAN type"
      lineinfile: dest=/etc/sysconfig/network regexp='^VLAN_NAME_TYPE=.*' line="VLAN_NAME_TYPE=DEV_PLUS_VID_NO_PAD" state=present

    - name: "manually load module"
      modprobe: name=8021q state=present

