---
- name: Update packages exclusivelly for COMPUTE nodes
  hosts: compute_backend
  sudo: yes

  tasks:
    - name: ensure virsh packages are installed
      yum: name={{ item.package }} state={{ item.state }}
      with_items:
        - { package: '@virtualization-platform', state: latest }
        - { package: '@virtualization-tools', state: latest}
      notify:
         - restart libvirtd

    - name: ensure libvirtd boots automatically after reboot
      service: name=libvirtd state=started enabled=yes

        
    - name: ensure vibr0 is stopped
      command: /usr/bin/virsh net-destroy default
      ignore_errors: True
      notify:
         - restart libvirtd
      
    - name: ensure vibr0 is disabled
      command: /usr/bin/virsh net-autostart default --disable
      ignore_errors: True
      notify:
         - restart libvirtd


  handlers:
    - name: restart libvirtd
      service: name=libvirtd state=restarted



