---
- name: update kernel for Network, Compute
  hosts: network_gateway:compute_backend
  sudo: yes

  tasks:
    - name: ensure openstack kernel is installed
      yum: name={{ openstack_kernel }} state=latest
      notify: reboot host

      
  handlers:
    - name: reboot host
      shell: sleep 2s && /sbin/reboot &
      notify: wait for the server to come up(max 10min)

    - name: wait for the server to come up(max 10min)
      local_action: wait_for host={{ inventory_hostname }} port=22 delay=30 timeout=600
