---
- name: OpenStack Telemetry (mongoDB)
  hosts: ceilometer_db_backend
  sudo: yes

  tasks:
 
               
    - name: ensure mongodb repository file is installed
      copy: src=templates/etc/yum.repos.d/mongodb.repo dest=/etc/yum.repos.d/mongodb.repo owner=root group=root mode=0644

    - name: yum clean all
      command: /usr/bin/yum clean all

    - name: ensure database for cinder is installed
      yum: name={{item}} state=latest
      with_items:
        - mongo-10gen
        - mongo-10gen-server
      notify:
        - restart mongoDB service
 
    - name: configure mongoDB bind address
      lineinfile: >
        dest=/etc/mongod.conf
        regexp=^bind_ip=
        line=bind_ip={{my_int_ip}},127.0.0.1
      notify:
        - restart mongoDB service

    
    - name: ensure mongoDB port 27017 is opened
      include: ../reusables/open_firewall_port.yml protocol=tcp port=27017
      
    - name: ensure mongoDB is started
      service: name={{ item }} state=started
      with_items: 
        - mongod
      
    - name: ensure mongoDB automatically boots after reboot
      service: name={{ item }} enabled=yes
      with_items: 
        - mongod
        
  handlers:
    - include: ../reusables/handlers.yml
    - name: restart mongoDB service
      service: name={{ item }} state=restarted
      with_items: 
        - mongod
