---
- name: OpenStack Telemetry (Frontend)
  hosts: frontend
  sudo: yes

  tasks:
 
    - name: ensure Ceilometer-related packages are installed
      yum: name={{item}}  state=latest
      with_items:
        - openstack-ceilometer-api
        - python-ceilometer
        - openstack-selinux
        - python-ceilometerclient
      notify:
       - restart ceilometer services

    - name: ensure ceilometer.conf file is configured
      template: >
        src=templates/etc/ceilometer/ceilometer.conf
        dest=/etc/ceilometer/ceilometer.conf
        owner=root group=ceilometer mode=0640 backup=no
      notify:
       - restart ceilometer services
    
    - name: ensure ceilometer port 8777 is opened
      include: ../reusables/open_firewall_port.yml protocol=tcp port=8777

    - name: ensure ceilometer services are started
      service: name={{ item }} state=started
      with_items: 
        - openstack-ceilometer-api
      
    - name: ensure ceilometer automatically boots after reboot
      service: name={{ item }} enabled=yes
      with_items: 
        - openstack-ceilometer-api
        
  handlers:
    - include: ../reusables/handlers.yml
    - name: restart ceilometer services
      service: name={{ item }} state=restarted
      with_items: 
        - openstack-ceilometer-api
