---
- name: Memcached
  hosts: controller
  sudo: yes

  tasks:
    - name: ensure memcached package is installed
      yum: name=memcached state=latest

    - name: ensure port 11211 is opened
      include: ../reusables/open_firewall_port.yml protocol=tcp port=11211

    - name: ensure memcached local settings
      template: >
          src=templates/etc/sysconfig/memcached
          dest=/etc/sysconfig/memcached
          owner=root
          group=root
          mode=0644
      notify: restart memcached
      

    - name: ensure memcached runs automatically after boot.
      service: name=memcached state=started enabled=yes


  handlers:
    - include: ../reusables/handlers.yml
    
    - name: restart memcached
      service: name=memcached state=restarted


