---
- name: OpenStack Block Storage (Frontend)
  hosts: frontend
  sudo: yes

  tasks:
 
    - name: ensure cinder-related packages are installed
      yum: name={{item}}  state=latest
      with_items:
        - openstack-cinder
        - openstack-utils
        - openstack-selinux
        - MySQL-python
      notify:
       - restart cinder services

    - name: ensure cinder.conf file is configured
      template: >
        src=templates/etc/cinder/cinder.conf
        dest=/etc/cinder/cinder.conf
        owner=root group=cinder mode=0640 backup=no
      notify:
       - restart cinder services
    
    - name: ensure cinder port 8776 is opened
      include: ../reusables/open_firewall_port.yml protocol=tcp port=8776

      
      # cinder_manage looks for flags.py which is no longer used?
    - name: ensure cinder database is synchronized
      command: su cinder -s /bin/sh -c "cinder-manage db sync"
      notify: restart cinder services
      
      
    - name: ensure cinder automatically boots after reboot
      service: name={{ item }} state=started enabled=yes
      with_items: 
        - openstack-cinder-api
        
  handlers:
    - include: ../reusables/handlers.yml
    - name: restart cinder services
      service: name={{ item }} state=restarted
      with_items: 
        - openstack-cinder-api
